// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var Conntrack = NewRuntimeAsset("conntrack.c", "1b9590903a4a9e2fcda49546068de5fff238067cc280fba6dc895ab0ffe9cab1")
