// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "33bc698ae544b8d0064545367641d2a7e55f76a0657ea94bf94c992442a44237")
