// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "189214e0ef49b1333fe36e6246f668779524577998ec408236d0067b0f3dc304")
