// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "53ff1bcef02a958d46d852e252129246238120746aace799d675774bc342b5d2")
